openapi: 3.1.0
info:
  title: Winderoo API
  version: 2.0.0
servers:
  - url: http://winderoo.local/api/
    description: local development and deployed devices
tags:
  - name: Status
    description: Retrieve the current state of Winderoo
  - name: Modify
    description: Modify the state of Winderoo
paths:
  /update:
    post:
      tags:
        - Modify
      summary: Change the state of Winderoo
      requestBody:
        $ref: '#/components/requestBodies/UpdateBody'
      responses:
        '204':
          description: Successful opeation
        '500':
          description: Something went wrong when writing to memory
  /status:
    get:
      tags:
        - Status
      summary: Get the current status of Winderoo
      responses:
        '200':
          description: Service is alive with current winder state
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /power:
    post:
      tags:
        - Modify
      summary: Toggle whether Winderoo is on or off (hard off state)
      responses:
        '204':
          description: State toggled succesfully
  /reset:
    get:
      tags:
        - Modify
      summary: Resets Winderoo's network settings; re-initializes winderoo with setup access point
      responses:
        '200':
          description: State toggled succesfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resetting'
components:
  requestBodies:
    UpdateBody:
      description: a JSON object containing winderoo information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Update'
          example:
            tpd: "330"
            hour: "14"
            minutes: "50"
            timerEnabled: "0"
            action: "START"
            rotationDirection: "BOTH"
  schemas:
    Update:
      type: object
      propertries:
        tpd:
          type: string
          description: how many turns are required
          examples:
            - 330
        hour:
          type: string
          description: At what hour winderoo should begin winding at
          examples:
            - 14
        minutes:
          type: string
          description: At what minute winderoo should begin winding at
          examples:
            - 50
        timerEnabled:
          type: string
          description:
            Whether Winderoo should enable alarm-start winding; number represents a boolean where 0 == off and 1 == on.
          examples:
            - 0
            - 1
        action:
          type: string
          description: Whether Winderoo should start or stop winding
          examples:
            - START
            - STOP
        rotationDirection:
          type: string
          description: The winding direction
          examples:
            - CW
            - CCW
            - BOTH
    Status:
      type: object
      properties:
        status:
          type: string
          examples: 
            - Stopped
        rotationsPerDay:
          type: string
          examples:
            - 300
        direction:
          type: string
          examples:
            - BOTH
        hour:
          type: string
          examples:
            - 12
        minutes:
          type: string
          examples:
            - 50
        durationInSecondsToCompleteOneRevolution:
          type: number
          examples:
            - 8
        startTimeEpoch:
          type: number
          examples:
            - 0
        currentTimeEpoch:
          type: number
          examples:
            - 1680555863
        estimatedRoutineFinishEpoch:
          type: number
          examples:
            - 0
        winderEnabled:
          type: string
          examples:
            - 1
        timerEnabled:
          type: string
          examples:
            - 1
        db:
          type: number
          examples:
            - -67
        networkedUnits:
          type: array
          items:
            $ref: '#/components/schemas/NetworkWinder'
    NetworkWinder:
      type: object
      properties:
        id:
          type: string
          examples:
            - 35c967d3-60a2-46b0-8674-2fdf7b675151
        status:
          type: string
          examples: 
            - Stopped
        direction:
          type: string
          examples:
            - BOTH
        rotationsPerDay:
          type: string
          examples:
            - 300
        meshStrength:
          type: number
          examples:
            - -67
    Resetting:
      type: object
      properties:
        status:
          type: string
          examples:
            - Resetting